SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE ONLY urbancity.producto DROP CONSTRAINT "FK_IDSUBCATEGORIA_PRODUCTO";
ALTER TABLE ONLY urbancity.carrito DROP CONSTRAINT "FK_IDREFERENCIA_PRODUCTO";
ALTER TABLE ONLY urbancity.pedpro DROP CONSTRAINT "FK_IDREFERENCIA_PEDPRO";
ALTER TABLE ONLY urbancity.pedpro DROP CONSTRAINT "FK_IDPEDIDO_PEDPRO";
ALTER TABLE ONLY urbancity.pedido DROP CONSTRAINT "FK_IDCLIENTE_PEDIDO";
ALTER TABLE ONLY urbancity.carrito DROP CONSTRAINT "FK_IDCLIENTE_CLIENTE";
ALTER TABLE ONLY urbancity.subcategoria DROP CONSTRAINT "FK_CATEGORIA_SUBCATEGORIA";
ALTER TABLE ONLY urbancity.guiatalla DROP CONSTRAINT guiatalla_pkey;
ALTER TABLE ONLY urbancity.subcategoria DROP CONSTRAINT "PK_IDSUBCATEGORIA_CATEGORIA";
ALTER TABLE ONLY urbancity.producto DROP CONSTRAINT "PK_IDREFERENCIA_PRODUCTO";
ALTER TABLE ONLY urbancity.pedido DROP CONSTRAINT "PK_IDPEDIDO_PEDIDO";
ALTER TABLE ONLY urbancity.pedpro DROP CONSTRAINT "PK_IDPEDIDO-IDREFERENCIA_PEDPRO";
ALTER TABLE ONLY urbancity.categoria DROP CONSTRAINT "PK_IDCATEGORIA_CATEGORIA";
ALTER TABLE ONLY urbancity.cliente DROP CONSTRAINT "PK_CLIENTE_IDCLIENTE";
ALTER TABLE ONLY urbancity.carrito DROP CONSTRAINT "FK_IDCARRITO_CARRITO";
ALTER TABLE urbancity.subcategoria ALTER COLUMN idsubcategoria DROP DEFAULT;
ALTER TABLE urbancity.pedido ALTER COLUMN idpedido DROP DEFAULT;
ALTER TABLE urbancity.guiatalla ALTER COLUMN idguia DROP DEFAULT;
ALTER TABLE urbancity.cliente ALTER COLUMN idcliente DROP DEFAULT;
ALTER TABLE urbancity.categoria ALTER COLUMN idcategoria DROP DEFAULT;
ALTER TABLE urbancity.carrito ALTER COLUMN idcarrito DROP DEFAULT;